---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
            args: ["--autofix"]
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: pretty-format-json
          - id: trailing-whitespace
    - repo: https://github.com/ansible/ansible-lint
      rev: v4.3.0a1
      hooks:
          - id: ansible-lint
            files: \.(yaml|yml)$
    - repo: https://github.com/codespell-project/codespell
      rev: v1.17.1
      hooks:
          - id: codespell
            args: [--ignore-words=.codespell-ignores]
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.23.0
      hooks:
          - id: yamllint
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
