---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-added-large-files
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
            args: ["--autofix"]
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: name-tests-test
          - id: pretty-format-json
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.5.1
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-mock-methods
          - id: python-no-log-warn
    - repo: https://github.com/ansible/ansible-lint
      rev: v4.3.0a1
      hooks:
          - id: ansible-lint
            files: \.(yaml|yml)$
    - repo: https://github.com/codespell-project/codespell
      rev: v1.17.1
      hooks:
          - id: codespell
            args: [--ignore-words=.codespell-ignores]
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.6.1
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.23.0
      hooks:
          - id: yamllint
    - repo: https://github.com/prettier/prettier
      rev: 2.0.5
      hooks:
          - id: prettier
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.6
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            args: [--config=.flake8]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.780
      hooks:
          - id: mypy
