---
- hosts: localhost
  vars_files:
      - vars/main.yml
  tasks:
      - include: tasks/setup.yml
        tags: ["always"]
      - include: tasks/chronyd.yml
        tags: ["always"]
        become: true
      - include: tasks/networking.yml
        become: true
      - include: tasks/packages.yml
        become: true
        tags: ["packages"]
      - include: tasks/configs.yml
        tags: ["configs"]
      - include: tasks/users.yml
      - include: tasks/git.yml
        become: true
      - include: tasks/repos.yml
        tags: ["repos"]
      - include: tasks/go.yml
        tags: ["go"]
      - include: tasks/podman.yml
        tags: ["podman"]
      - include: tasks/cron.yml
      - include: tasks/cleanup.yml
        tags: ["always"]
