---
# TODO(rkm 2020-08-16) Convert these to roles: "boot" and "login"

- hosts: localhost
  vars_files:
      - vars/main.yml
  tasks:
      - include: tasks/setup.yml
        tags: [always]

      - include: tasks/chronyd.yml
        become: true
        tags: [always]

      - include: tasks/networking.yml
        become: true
        tags: [never, boot]

      - include: tasks/packages.yml
        become: true
        tags: [never, boot, packages]

      - include: tasks/configs.yml
        tags: [never, boot, user, configs]

      - include: tasks/sudoers.yml
        tags: [never, boot]

      - include: tasks/git.yml
        become: true
        tags: [never, boot, git]

      - include: tasks/python.yml
        tags: [never, user, python]

      - include: tasks/repos.yml
        tags: [never, user, repos]

      - include: tasks/go.yml
        tags: [never, boot, go]

      - include: tasks/podman.yml
        tags: [never, boot, podman]

      - include: tasks/cron.yml
        tags: [never, boot]

      - include: tasks/cleanup.yml
        tags: [always]
