---

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yml
  # environment:
  #   - PATH: /usr/local/bin:{{ ansible_env.PATH  }}
  tasks:
    - include: tasks/setup.yml
      tags: ['always']
    - include: tasks/configs.yml
      tags: ['configs']
    - include: tasks/users.yml
    - include: tasks/packages.yml    
    - include: tasks/git.yml
    # - include: tasks/python.yml
    #   tags: ['python']
    # - include: tasks/go.yml
    #   tags: ['go']
    # - include: tasks/azure_cli.yml
    # - include: tasks/dev.yml
    #   tags: ['dev']
    - include: tasks/cleanup.yml
      tags: ['always']
