---
- name: Check if az CLI installed
  command: which az
  register: az_result
  failed_when: false
  changed_when: false

- name: Install Azure CLI - repo key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: az_result.rc != 0

- name: Install Azure CLI - create repo
  shell: |
    echo "
    [azure-cli]
    name=Azure CLI
    baseurl=https://packages.microsoft.com/yumrepos/azure-cli
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    " > /etc/yum.repos.d/azure-cli.repo
  when: az_result.rc != 0

- name: Install Azure CLI - yum package
  yum:
    name:
      - azure-cli
  when: az_result.rc != 0
