---

- name: Register version check
  command: az --version
  register: current_version
  ignore_errors: true
  changed_when: current_version.rc != 0

- name: Install Azure CLI - repo key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: current_version.rc != 0

- name: Install Azure CLI - create repo
  shell: |
    echo "
    [azure-cli]
    name=Azure CLI
    baseurl=https://packages.microsoft.com/yumrepos/azure-cli
    enabled=1
    gpgcheck=1
    gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    " > /etc/yum.repos.d/azure-cli.repo
  when: current_version.rc != 0

- name: Install Azure CLI - yum package
  yum:
    name:
      - azure-cli
