---

- name: Ensure $XDG_DATA_HOME (.config) exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Create $XDG_DATA_HOME appliction directories
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/{{ item }}"
    state: directory
  with_items:
    - git
    - vim

- name: Download dotfiles archive
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: Unarchive the dotfiles
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: yes
    list_files: yes
  changed_when: false # Will always be changed
  register: archive_contents

- name: Create combined .gitconfig
  shell: >
    cat
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/common/.gitconfig"
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/.gitconfig"
    > "{{ tempdir.path }}/dotfiles/.gitconfig"
  changed_when: false # Will always be changed

- name: Copy combined .gitconfig
  copy:
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/.gitconfig"
    remote_src: true
    dest: /home/{{ username }}/.config/git/config
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0640
    backup: true

- name: Copy dotfiles
  copy:
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/{{ item }}"
    remote_src: true
    dest: /home/{{ username }}/{{ item }}
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0640
    backup: true
  with_items:
    - .bashrc
    - .bash_aliases
    - .bash_aliases_azure
    - .inputrc
    - .vimrc
