---
- name: Ensure the config and data directories exist
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: directory
    mode: u=rwx,g=rwx,o=
  with_items:
    - .config
    - .config/containers
    - .config/git
    - .config/maven
    - .config/npm
    - .config/vim
    - .local
    - .local/share
    - .local/share/cargo
    - .local/share/rustup
    - .local/share/stack
    - .local/share/vim
    - .local/share/vim/backup
    - .local/share/vim/swap
    - .local/share/vim/undo
    - .local/share/vim/view

- name: Download dotfiles archive
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: Unarchive the dotfiles
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: true
    list_files: true
  changed_when: false # Will always be changed
  register: archive_contents

- name: Create combined .gitconfig
  shell: >
    cat
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/common/gitconfig"
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/gitconfig"
    > "{{ tempdir.path }}/gitconfig"
  changed_when: false # Will always be changed

- name: Copy combined gitconfig
  copy:
    src: "{{ tempdir.path }}/gitconfig"
    remote_src: true
    dest: "{{ lookup('env', 'HOME') }}/.config/git/config"
    mode: 0660
    backup: true

- name: Copy configs
  copy:
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/"
    remote_src: true
    dest: "{{ lookup('env', 'HOME') }}/.config/"
    mode: 0770
    backup: true

- name: Copy scripts
  copy:
    src: files/{{ item }}
    dest: /home/{{ username }}/.local/bin
    mode: 0770
    remote_src: true
    backup: true
  with_items:
    - au
    - bash_login

- name: Copy bash dotfiles
  copy:
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/{{ item }}"
    dest: /home/{{ username }}/.{{ item }}
    mode: 0660
    remote_src: true
    backup: true
  with_items:
    - bash_aliases
    - bash_login
    - bashrc
    - profile

# NOTE(rkm 2020-04-24) Ensures that .profile is always executed
- name: Remove .bash_profile
  file:
    path: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: absent
  with_items:
    - ".bash_profile"
