---

- name: Ensure $XDG_DATA_HOME (.config) exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Create $XDG_DATA_HOME appliction directories
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/{{ item }}"
    state: directory
  with_items:
    - git
    - readline
    - vim
    - vim/backup
    - vim/swap
    - vim/undo

- name: Download dotfiles archive
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: Unarchive the dotfiles
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: yes
    list_files: yes
  changed_when: false # Will always be changed
  register: archive_contents

- name: Create combined .gitconfig
  shell: >
    cat
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/common/.gitconfig"
    "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/.gitconfig"
    > "{{ tempdir.path }}/.gitconfig"
  changed_when: false # Will always be changed

- name: Copy combined .gitconfig
  copy:
    src: "{{ tempdir.path }}/.gitconfig"
    remote_src: true
    dest: "{{ lookup('env', 'HOME') }}/.config/git/config"
    mode: 0660
    backup: true

- name: Copy configs
  copy: 
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/{{ item.src }}"
    remote_src: true
    dest: "{{ lookup('env', 'HOME') }}/.config/{{ item.dest }}"
    mode: 0660
    backup: true
  with_items:
    - {src: ".vimrc", dest: "vim/vimrc"}
    - {src: ".inputrc", dest: "inputrc"}

- name: Copy bash dotfiles
  copy:
    src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/{{ item }}"
    dest: /home/{{ username }}/{{ item }}
    mode: 0660
    remote_src: true
    backup: true
  with_items:
    - .bashrc
    - .bash_aliases
    - .bash_aliases_azure
    - .profile
