---
- name: Copy ansible cron script
  copy:
    src: "ansible_pull_cron"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/ansible_pull_cron"
    mode: 0770
    backup: true

- name: Ensure a cron entry for ansible_pull_cron exist
  become: "{{ username }}"
  cron:
    name: "runs ansible-pull on reboot"
    special_time: reboot
    job: "{{ lookup('env', 'HOME') }}/.local/bin/ansible_pull_cron"
