---
- name: Download crun
  get_url:
      url: https://github.com/alvistack/crun/releases/download/0.14.1/crun-{{ crun_version }}-linux-amd64
      dest: /home/{{ username }}/.local/bin/crun-{{ crun_version }}
      mode: "0770"

- name: Symlink crun
  file:
      src: /home/{{ username }}/.local/bin/crun-{{ crun_version }}
      dest: /home/{{ username }}/.local/bin/crun
      state: link
      mode: "0770"
