---
# TODO(rkm 2020-08-23) use allowerasing when we have ansible 2.10
- name: Install dotnet dependencies
  become: true
  shell: dnf -y --allowerasing install libcurl libicu zlib openssl-libs compat-openssl10 krb5-libs
  args:
      warn: false
  register: result
  changed_when: result.rc != 0

- name: Check current version
  shell: "dotnet --version"
  failed_when: false
  changed_when: false
  register: dotnet_result

- name: Set dotnet install fact
  set_fact:
      dotnet_need_install: "{{ dotnet_result.rc != 0 or dotnet_sdk_version not in dotnet_result.stdout }}"

- name: Download the dotnet install script
  get_url:
      url: https://dot.net/v1/dotnet-install.sh
      dest: "{{ tempdir.path }}"
      mode: "0770"
      checksum: "sha256:3c24b6b3ca3cbf1d9167cff53ae9d5079199f6eed3b5dcf9d6b2bf34cc4dc329"
  when: dotnet_need_install

- name: Install dotnet
  shell: "{{ tempdir.path }}/dotnet-install.sh --version {{ dotnet_sdk_version }} --install-dir {{ lookup('env', 'HOME') }}/.local/lib/dotnet"
  when: dotnet_need_install

- name: Create symlink to dotnet
  file:
      src: "{{ lookup('env', 'HOME') }}/.local/lib/dotnet/dotnet"
      dest: "{{ lookup('env', 'HOME') }}/.local/bin/dotnet"
      state: link
