---

- name: Check installed version
  command: "{{ git_install_path }}/bin/git --version"
  changed_when: false
  failed_when: false
  check_mode: false
  register: git_installed_version

- name: Force git install if the version numbers do not match
  set_fact:
    git_reinstall_from_source: true
  when: >
    git_installed_version.rc != 0 or
    (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1")
      is version(git_version, operator="!="))

- name: Set git role workspace to the tempdir
  set_fact:
    workspace: "{{ tempdir.path }}"
  when:
    - git_reinstall_from_source | default(false)

- name: Run geerlingguy.git
  include_role:
    name: geerlingguy.git
  when:
    - git_reinstall_from_source | default(false)
