---

- name: Run gantsign.golang
  include_role:
    name: gantsign.golang

- name: Link to /usr/local/bin
  become: true
  file:
    src: /usr/local/go/{{ golang_version }}/bin/go
    dest: /usr/local/bin/go
    owner: root
    group: root
    state: link

- name: Install go packages
  command: go get -u {{ item }}
  with_items:
    - github.com/tomnomnom/gron
  changed_when: false
