---
- name: Run gantsign.golang
  include_role:
      name: gantsign.golang

- name: Link to /usr/local/bin
  become: true
  file:
      src: "{{ golang_install_dir }}/bin/go"
      dest: /opt/bin/go
      owner: root
      group: root
      state: link

- name: Install go packages
  command: go get -u {{ item }}
  with_items:
      - github.com/tomnomnom/gron
  changed_when: false
  when: false # NOTE(rkm 2020-08-24) Seems to be broken after go 1.15
