---

- name: dnf update
  package:
    name: "*"
    state: latest  # noqa: 403

- name: Install dnf packages
  package:
    name:
      - bzip2
      - curl
      - dkms
      - gcc
      - gdb
      - htop
      - kernel-headers
      - kernel-devel
      - net-tools
      - nmap
      - perl
      - rsync
      - screen
      - strace
      - telnet
      - traceroute
      - vim
      - wget

- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp
#   when: not lookup('env', 'DOCKER')

- name: Set docker username
  set_fact:
    docker_users: ["{{ username }}"]

- name: Run geerlingguy.docker
  include_role:
    name: geerlingguy.docker

# - name: Run geerlingguy.java
#   include_role:
#     name: geerlingguy.java

# - name: Run geerlingguy.ruby
#   include_role:
#     name: geerlingguy.ruby

# - name: Run rkm.dotnet_core
#   include_role:
#     name: rkm.dotnet_core
