---

- name: Ensure /opt/bin exists
  file:
    path: /opt/bin
    state: directory

- name: dnf update
  package:
    name: "*"
    state: latest  # noqa: 403

# TODO(rkm 2020-04-27) Move these to a vars array
- name: Install dnf packages
  package:
    name:
      - bind-utils
      - bzip2
      - clang
      - clang-devel
      - curl
      - dkms
      - gcc
      - gdb
      - htop
      - jq
      - kernel-devel
      - kernel-headers
      - llvm
      - llvm-devel
      - net-tools
      - nmap
      - perl
      - rsync
      - screen
      - strace
      - telnet
      - traceroute
      - vim
      - wget

- name: Run geerlingguy.ntp
  include_role:
    name: geerlingguy.ntp

- name: Set docker username
  set_fact:
    docker_users: ["{{ username }}"]

- name: Run geerlingguy.docker
  include_role:
    name: geerlingguy.docker
