---
- name: template the dockerfile
  template:
      src: templates/podman.Dockerfile.j2
      dest: "{{ tempdir.path }}/podman.Dockerfile"
  changed_when: false

- name: ensure pip docker lib is installed
  pip:
      name: docker
      extra_args: --user
      executable: pip3.6

- name: build the podman builder image
  docker_image:
      build:
          path: "{{ tempdir.path }}"
          dockerfile: podman.Dockerfile
          pull: no
      name: ansible_podman_builder
      source: build

- name: extract the rpm from the image
  docker_container:
      detach: false
      name: ansible_podman_builder
      image: ansible_podman_builder
      volumes:
          - "{{ tempdir.path }}:/vol"
      user: "{{ lookup('env', 'UID') }}:{{ lookup('env', 'UID') }}"
      state: started

- name: install the podman rpm
  become: true
  package:
      name: "{{ tempdir.path }}/podman-{{ podman_version }}.rpm"
      state: present

- name: remove the podman container
  docker_container:
      name: ansible_podman_builder
      state: absent
      force_kill: true

- name: remove the podman image
  docker_image:
      name: ansible_podman_builder
      state: absent
      force_absent: true
