---
- name: template the dockerfile
  template:
      src: templates/podman.Dockerfile.j2
      dest: "{{ tempdir.path }}/podman.Dockerfile"

- name: build the podman builder image
  docker_image:
      build:
          path: "{{ tempdir.path }}"
          dockerfile: podman.Dockerfile
          pull: no
      name: ansible_podman_builder
      source: build

- name: extract the rpm from the image
  docker_container:
      detach: false
      name: ansible_podman_builder
      image: ansible_podman_builder
      volumes:
          - "{{ tempdir.path }}:/vol"
      user: "{{ lookup('env', 'UID') }}:{{ lookup('env', 'UID') }}"
      state: started

- name: install the podman rpm
  become: true
  package:
      name: "{{ tempdir.path }}/podman-{{ podman_version }}.rpm"
      state: present
