---
- name: register installed package versions
  package_facts:
      manager: auto

- name: determine if podman needs to be installed
  set_fact:
      # Multiple versions?
      podman_require_install: "{{ 'podman' not in ansible_facts.packages or ansible_facts.packages['podman'][0].version != podman_version }}"

- name: build & install podman
  include_tasks: podman_build.yml
  when: podman_require_install

- name: check crun version
  shell: |
      /home/{{ username }}/.local/bin/crun --version
  register: crun_check
  changed_when: false
  failed_when: false

- name: install crun
  include_tasks: crun_install.yml
  when: crun_version not in crun_check.stdout
