---

- name: Get all personal repos
  shell: |
    set -o pipefail
    curl https://api.github.com/users/rkm/repos |
    jq -r '.[] | .full_name'
  changed_when: false
  register: personal_repos_result

- name: Build repo list
  set_fact:
    persistent_repos: "{{ personal_repos_result.stdout_lines | list + persistent_repos }}"

- name: Clone repos  # noqa: 401
  git:
    accept_hostkey: true
    dest: /home/rkm/dev/{{ item }}
    executable: "{{ git_install_path }}/bin/git"
    repo: git@github.com:{{ item }}
    ssh_opts: -o StrictHostKeyChecking=no
    update: false
  with_items: "{{ persistent_repos }}"

- name: Fetch all repos
  shell: |
    set -o pipefail
    find {{ lookup('env', 'HOME') }}/dev -type f -name .git |
    xargs dirname |
    xargs -l -I{} git -C {} fetch --all --prune
  register: fetch_result
  changed_when: fetch_result.rc != 0

# NOTE(rkm 2020-05-02) Uses the prune tags git alias
- name: Prune tags
  shell: |
    set -o pipefail
    find {{ lookup('env', 'HOME') }}/dev -type f -name .git |
    xargs dirname |
    xargs -l -I{} git -C {} pt
  register: fetch_result
  changed_when: fetch_result.rc != 0

# TODO(rkm 2020-04-27) Clone docs + notebooks
# TODO(rkm 2020-04-2&) Link alan-turing-institute -> ati
# TODO(rkm 202-05-02) Do the same for SMI as for rkm org
