---

- name: Clone repos  # noqa: 401
  git:
    accept_hostkey: true
    dest: /home/rkm/dev/{{ item }}
    executable: "{{ git_install_path }}/bin/git"
    repo: git@github.com:{{ item }}
    ssh_opts: -o StrictHostKeyChecking=no
    update: false
  with_items: "{{ persistent_repos }}"

- name: Fetch all repos
  shell: |
    set -o pipefail
    find {{ lookup('env', 'HOME') }}/dev -type f -name .git |
    xargs dirname |
    xargs -l -I{} git -C {} fetch --all --prune
  register: fetch_result
  changed_when: fetch_result.rc != 0

# TODO(rkm 2020-04-27) Clone docs + notebooks
# TODO(rkm 2020-04-27) Replace rkm/* repos with API call to get latest
# TODO(rkm 2020-04-2&) Link alan-turing-institute -> ati
