---

- name: Clone repos  # noqa: 401
  git:
    executable: "{{ git_install_path }}/bin/git"
    repo: git@github.com:{{ item }}
    dest: /home/rkm/dev/{{ item }}
    update: false
  with_items:
     - rkm/ansible-role-dotnet-core
     - rkm/dotfiles
     - rkm/personal-centos8
     - rkm/serenity
     - smi/SmiServices
     - smi/integration
     - HicServices/BadMedicine
     - HicServices/BadMedicine.Dicom
     - HicServices/DicomTemplateBuilder
     - HicServices/DicomTypeTranslation
     - HicServices/FAnsiSql
     - HicServices/RDMP
     - HicServices/RDMPDicom
     - alan-turing-institute/aviary
     - alan-turing-institute/bluebird
     - alan-turing-institute/bluesky
     - alan-turing-institute/DataScienceSkills
     - alan-turing-institute/dodo
     - alan-turing-institute/nats
     - alan-turing-institute/nats-birdhouse
     - alan-turing-institute/simurgh
     - alan-turing-institute/twitcher

# TODO(rkm 2020-04-27) Fetch all
# TODO(rkm 2020-04-27) Clone docs + notebooks
# TODO(rkm 2020-04-27) Replace rkm/* repos with API call to get latest
# TODO(rkm 2020-04-2&) Link alan-turing-institute -> ati
