---

- name: Clone repos  # noqa: 401
  git:
    accept_hostkey: true
    dest: /home/rkm/dev/{{ item }}
    executable: "{{ git_install_path }}/bin/git"
    repo: git@github.com:{{ item }}
    ssh_opts: -o StrictHostKeyChecking=no
    update: false
  with_items: "{{ persistent_repos }}"

# TODO(rkm 2020-04-27) Fetch all
# TODO(rkm 2020-04-27) Clone docs + notebooks
# TODO(rkm 2020-04-27) Replace rkm/* repos with API call to get latest
# TODO(rkm 2020-04-2&) Link alan-turing-institute -> ati
