---
- name: Copy ssh host config
  template:
    src: templates/ssh_host_config.j2
    dest: /etc/ssh/ssh_config
    mode: u=rw,g=,o=
  register: result

- name: Restart sshd # noqa no-handler
  systemd:
    name: sshd
    state: restarted
  when: result.changed
