---
- name: Copy ssh host config
  template:
    src: templates/ssh_host_config.j2
    dest: /etc/ssh/ssh_config
  register: result

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
  when: result.changed
