---

- name: Stat ssh key files
  stat:
    path: "{{ lookup('env', 'HOME') }}/.ssh/{{ item }}"
  register: ssh_stat
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Assert ssh keys exist
  fail:
    msg: "Key missing: {{ item.invocation.module_args.path }}"
  when:
    - not item.stat.exists | bool
  with_items:
    - "{{ ssh_stat.results[0] }}"
    - "{{ ssh_stat.results[1] }}"

- name: Assert ssh key modes
  fail:
    msg: >-
      "Incorrect mode for key: {{ item.invocation.module_args.path }}."
      "Required 0400, current {{ item.stat.mode }}"
  when:
    - item.stat.mode != '0400'
  with_items:
    - "{{ ssh_stat.results[0] }}"
    - "{{ ssh_stat.results[1] }}"
