#!/usr/bin/env bash

# https://www.putorius.net/lock-files-bash-scripts.html
# shellcheck disable=SC2188
if { set -C; 2>/dev/null >~/.au.lock; }; then
    trap "rm -f ~/.au.lock" EXIT
else
    echo "Lock file exists - exiting"
    exit
fi

# shellcheck source=/dev/null
. "$HOME"/.profile
rm ~/.au.boot.log
ansible-pull -U https://github.com/rkm/personal-centos8 --tags boot &> ~/.au.boot.log
